Feature/thepapercn crawler
v2land/v2land-diamond-hoe pull request #5
Opened 2020-01-05 10:42 UTC by Ara-yjx

2020-01-05 13:59 UTC, zehua99 requested changes

2020-01-05 13:59 UTC, incrediblink commented on src/sites/thepaper.cn/index.ts
> +  public async init(): Promise<Crawler> {
原先的 init 方法需要 override 吗，原先网易新闻有这个是因为他们做了访问频率的限制。

2020-01-05 13:59 UTC, incrediblink commented on src/sites/thepaper.cn/index.ts
> +      return _.uniq(urls);
注意一下我改的几个代码风格吧

2020-01-06 16:20 UTC, Ara-yjx commented
现在应该🉑了

2020-01-07 05:44 UTC, zehua99 approved these changes
Yay!

2020-01-07 05:44 UTC, merged

2020-01-07 05:45 UTC, incrediblink commented
Merged.